from __future__ import annotations
from dataclasses import dataclass, field, fields
from beartype import beartype
from scipy.interpolate import interp1d
import traceback as tb
from beartype.typing import Any, Dict, Optional
from emcee import EnsembleSampler
from emcee.backends.backend import Backend
from emcee.backends.hdf import HDFBackend
import matplotlib.pyplot as plt
import matplotlib as mpl
import pickle, os, copy, sys
import numpy as np
from .. import utils
from ..errors import *
from ..utils import IntLike, Array1D, Array2D, Scalar
from .config import Config
from .line_list import LineList

# Try import dynesty if available and fail silently, only raises later if dynesty is chosen
try:
    from dynesty.sampler import Sampler
except ImportError:
    Sampler = None


@beartype
@dataclass(slots=True)
class Data:
    """
    Stores necessary data for the Acid class which can be conveniently updated and saved.
    Allows ACID to handle data that has already been computed to avoid recalculation. This class
    is designed to be lightweight in memory and hence does not store the sampler as an object. This is handled in the Result class.
    Note that a Data class should only hold the data for ONE order or observation, but it can hold
    the data for multiple frames of the same order.
    """

    # The standard necessary inputs, stored in dictionaries so we can store their state at multiple different
    # states of the calculations in Acid
    # -------------------------------------------------------------------------------------------------------
    #: The wavelengths for each frame, stored as a dictionary with frame names as keys and 1D numpy arrays as values.
    wavelengths : Dict[str, np.ndarray] = field(default_factory=dict)
    #: The fluxes for each frame, stored as a dictionary with frame names as keys and 1D numpy arrays as values.
    flux        : Dict[str, np.ndarray] = field(default_factory=dict)
    #: The errors for each frame, stored as a dictionary with frame names as keys and 1D numpy arrays as values.
    errors      : Dict[str, np.ndarray] = field(default_factory=dict)
    #: The signal-to-noise ratio for each frame, stored as a dictionary with frame names as keys and 1D numpy arrays as values.
    sn          : Dict[str, np.ndarray] = field(default_factory=dict)

    # Generated arrays from the above inputs, stored in dictionaries so we can store their state at multiple different stages
    # -------------------------------------------------------------------------------------------------------
    #: The normalised wavelengths to be used with the poly_coeffs to generate the continuum
    norm_wavelengths : Dict[str, np.ndarray] = field(default_factory=dict)
    #: The fitted flux from either the initial continuum fits, or the final mcmc fitted continua
    fitted_flux      : Dict[str, np.ndarray] = field(default_factory=dict)
    #: The fitted errors from either the initial continuum fits, or the final mcmc fitted continua
    fitted_errors    : Dict[str, np.ndarray] = field(default_factory=dict)
    #: The fitted continuum from either the initial continuum fits, or the final mcmc fitted continua
    continuum        : Dict[str, np.ndarray] = field(default_factory=dict)
    #: The error on the fitted continuum, only used after mcmc fitting, as this is the only important error for final profiles
    continuum_error  : Dict[str, np.ndarray] = field(default_factory=dict)
    #: The corresponding polynomial coefficients for just the above continuum
    poly_coeffs      : Dict[str, np.ndarray] = field(default_factory=dict)

    # Cached LSD products that can be expensive and useful for resuming or loading runs
    # ---------------------------------------------------------
    #: The alpha vector used in the linear model, used for solving the linear system in MCMC
    alpha                  : Dict[str, np.ndarray] = field(default_factory=dict)
    #: The forward model x-axis for each frame, used for solving the linear system in MCMC
    forward_x              : Dict[str, np.ndarray] = field(default_factory=dict)
    #: The forward model y-axis for each frame, used for solving the linear system in MCMC
    forward_y              : Dict[str, np.ndarray] = field(default_factory=dict)
    #: Tuple generated by np.cho_factor, used for solving the linear system in MCMC - paired with alpha_fitting
    c_factor               : Dict[str, tuple]      = field(default_factory=dict)
    #: The profile for each frame, used for solving the linear system in MCMC idx 0 is the profile, 1 is the errors, and 2 is the cov. matrix
    profile                : Dict[str, list]       = field(default_factory=dict)
    #: The residuals between the forward model and flux used to generate said model. Scaled to the forward model flux.
    residuals              : Dict[str, np.ndarray] = field(default_factory=dict)
    #: The indexes from the full linelist that was used in this LSD run
    ll_mask                : Dict[str, np.ndarray] = field(default_factory=dict)

    # Products generated from residual masking
    # ---------------------------------------------------------
    #: Boolean 1D mask on "initial" grid, used to mask out NaN/invalid values to go from initial to the combined spectra
    nanmask                : Optional[np.ndarray] = None
    #: Boolean 1D mask on "combined" grid, obtained from the MaskingLines class
    line_mask              : Optional[np.ndarray] = None
    #: Boolean 1D mask on "combined" grid, used for masking out pixels with high residuals in the residual masking step
    sigma_mask             : Optional[np.ndarray] = None
    #: Boolean 1D mask on "combined" grid, used for masking out pixels in the initial pixel masking step based on high SN or low SN
    pix_mask               : Optional[np.ndarray] = None
    #: Boolean 1D mask on "combined" grid, that is just a combination of the three above masks
    full_mask              : Optional[np.ndarray] = None

    # Small cached products needed for MCMC if doing reruns
    # -----------------------------------------------------
    #: The initial state of the MCMC walkers, used for resuming and debugging
    initial_state : Optional[np.ndarray] = None
    #: The number of walkers and dimensions for the MCMC sampler, used for reshaping the samples if resuming
    nwalkers      : Optional[int]        = None
    #: The number of dimensions for the MCMC sampler, used for reshaping the samples if resuming
    ndim          : Optional[int]        = None

    # Data required/calculated in results/after MCMC sampling
    # -------------------------------------------------------
    #: Same as the profile and profile errors above, but for all inputted frames and for only the final result. 0 returns the same as profile["final"] for first frame
    profiles : Optional[list] = None
    #: The number of steps taken in the MCMC sampling, used for checking convergence and for resuming
    nsteps   : Optional[int]  = 0
    #: A flag for whether the profiles have been fully calculated to avoid recalculating
    complete : bool           = False # is set to True when the profiles and final profile has been fully calculated

    # Other useful data and figures
    # -----------------------------
    #: The grouping of the profiles based on their depth, used for plotting and analysis
    profile_groups : Optional[np.ndarray] = None
    #: Internal variables used for plotting the continuum_fit and the residual masks
    plotting_variables   : Dict[str, Any]  = field(default_factory=dict)
    #: setup_time (float) - The time taken for initialization
    setup_time           : Optional[float] = 0  # time taken for initialization and setup
    #: mcmc_time (float) - The time taken for MCMC sampling
    mcmc_time            : Optional[float] = 0  # time taken for MCMC sampling
    #: results_time (float) - The time taken to get the final profiles
    results_time         : Optional[float] = 0 
    #: total_time (float) - The total time for the full run
    total_time           : Optional[float] = 0
    #: The exception class if an error was raised during the run
    exception            : Optional[Exception] = None
    #: The traceback string if an error was raised during the run
    traceback            : Optional[str] = None
    #: A tracker for if warnings have been printed in any LSD call
    lsd_warnings_flag    : bool = False
    #: If in debug mode (verbose = 4), debug data is stored as a dictionary here:
    debug                : Dict = field(default_factory=dict)
    #: Stored "in Windows" flag for setting up multiprocessing
    in_win = sys.platform == "win32"

    # Initialise the properties
    # -------------------------
    #: The sampler object stored as a class, but when saved, only a string to the HDF5 path is stored.
    _sampler    : Optional[EnsembleSampler|Sampler] = None # type:ignore
    #: Config data for convenience as a class, but converted to a dictionary on save to avoid pickling issues
    _config     : Config = field(default_factory=Config)
    #: The linelist is stored as a dictionary but exposed as a :py:class:`LineList` object when the property is accessed.
    _linelist   : Optional[Dict[str, np.ndarray]] = None
    #: The velocities are stored as a 1D numpy array
    _velocities : Optional[np.ndarray] = None

    def __repr__(self) -> str:
        """String representation of the Data object, showing all stored attributes in a user-friendly format."""
        ll_wl = self.linelist["wavelengths"]
        full_ll_range = [np.min(ll_wl), np.max(ll_wl)]
        cut_ll_range = [np.min(self.ll_mask["masked"]), np.max(self.ll_mask["masked"])]
        mp_lsd = self.profile_groups is not None

        output = [
            f"Number of velocity points: {len(self.velocities)}",
            f"deltav: {self.velocities[1] - self.velocities[0]} km/s",
            f"Number of linelist points (clipped/full): {len(self.ll_mask['masked'])} / {len(ll_wl)}",
            f"Linelist range (from-to, clipped/full): {cut_ll_range[0]}-{cut_ll_range[1]} / {full_ll_range[0]}-{full_ll_range[1]}",
            f"Order: {self.config.order}",
            f"Order range (min-max): {np.min(self.config.order_range)} - {np.max(self.config.order_range)}",
            f"Verbosity: {self.config.verbose}",
            f"Save path: {self.config.save_path}",
            f"Sampler path: {self.config.sampler_path}",
            f"Figure saving path: {self.config.figure_dir}",
            f"Using deterministic profile?: {self.config.deterministic_profile}",
            f"Polynomial order: {self.config.poly_ord}",
            f"Continuum percentile: {self.config.continuum_percentile}",
            f"Number of bins: {self.config.n_bins}",
            f"Bin size (number of points per bin, can be None): {self.config.bin_size}",
            f"Pixel chunk size: {self.config.pix_chunk}",
            f"Deviation percentage: {self.config.dev_perc}",
            f"Sigma lower: {self.config.sigma_lower}",
            f"Sigma upper: {self.config.sigma_upper}",
            f"Skips: {self.config.skips}",
            f"Using optical depth?: {self.config.od}",
            f"Using multi-profile LSD?: {mp_lsd}",
        ]

        if mp_lsd:
            output += [
                f"Depth group rules (can be None): {self.config.depth_group_rules}",
                f"Number of groups: {len(np.unique(self.profile_groups))}",
            ]

        output += [
            f"Sampler type: {self.config.sampler_type}",
            f"Parallel processing?: {self.config.parallel}",
            f"Number of cores: {self.config.cores}",
            f"Number of walkers: {self.nwalkers}",
            f"Number of dimensions: {self.ndim}",
            f"Number of steps (can be None): {self.config.nsteps}",
            f"Maximum number of steps (can be None): {self.config.max_steps}",
            f"Continuum method: {self.config.continuum_method}",
            f"Exception raised: {self.exception}",
        ]

        return "\n".join(output)

    @property
    def sampler(self) -> EnsembleSampler|Sampler|None: # type:ignore
        """
        The ensemble sampler object used for MCMC sampling.
        This is stored as a class variable but when saved, only the path to the sampler is stored to avoid pickling issues.
        """
        return self._sampler

    @sampler.setter
    def sampler(self, sampler:EnsembleSampler|Sampler|Backend|HDFBackend|str|None) -> None: # type:ignore
        """
        Sets the sampler object from various types.
        This is stored as a class variable but when saved, only the path to the sampler is stored to avoid pickling issues.
        """
        if sampler is not None:
            from ..mcmc import MCMC
            log_prob_fn = MCMC(self)

        if isinstance(sampler, EnsembleSampler):
            self._sampler = sampler
        elif Sampler is not None and isinstance(sampler, Sampler):
            self._sampler = sampler
        elif isinstance(sampler, Backend) or isinstance(sampler, HDFBackend):
            self._sampler = utils.backend_to_sampler(sampler, log_prob_fn)
        elif isinstance(sampler, str):
            if os.path.exists(sampler):
                self._sampler = utils.backend_to_sampler(HDFBackend(sampler), log_prob_fn)
            else:
                if self.config.verbose >= 1:
                    print(f"Warning: The sampler was not found at the provided path '{sampler}', it may have been moved or deleted. \n"
                          f"The sampler will be set to None.", flush=True)
                self._sampler = None
                # TODO: Allow sampler to have completed results, but no sampler, and configured methods with _requiresampler property that need them
        elif sampler is None:
            if self.config.verbose >= 1 and self._sampler is not None:
                print("Warning, you have discarded the sampler.")
            self._sampler = None
        
        if isinstance(self._sampler, EnsembleSampler) and isinstance(self._sampler.backend, HDFBackend):
            self.config.sampler_path = os.path.abspath(self._sampler.backend.filename)

    @property
    def velocities(self) -> Array1D|None:
        """The velocity grid to perform LSD on."""
        return self._velocities

    @velocities.setter
    def velocities(self, value:Array1D|None) -> None:
        """Sets and overwrites the velocity grid if the value is not None.
        If overwriting, resets the Data instance as calculations are dependent on velocities."""
        if value is not None:
            
            # First validate the input array
            velocities = np.array(value)
            if not np.all(np.isfinite(velocities)):
                raise ValueError("The velocity grid you are trying to set must all be finite and not contain NaNs")
            if len(velocities) <= 1:
                raise ValueError("The velocity grid you are trying to set must have more than 1 value to be valid.")
            v_diff = np.diff(velocities)
            if not np.all(np.allclose(v_diff, v_diff[0])):
                raise ValueError("The velocity grid you are trying to set must be evenly spaced.")

            # Set overwriting flag if velocities already exists and are different from new input
            overwriting = False
            if self._velocities is not None:
                if len(self._velocities) != len(velocities):
                    overwriting = True
                elif not np.allclose(self._velocities, velocities):
                    overwriting = True

            # Set velocities
            self._velocities = np.array(value)

            # Reset and warn if overwriting
            if overwriting:
                print("Warning: Overwriting existing velocities in Data. The Data instance will be reset to clear calculations that depend on the velocities.\n" \
                "The linelist, config, and original data inputs will not be reset.")
                self.reset()

        elif self._velocities is None:
            # If velocities is being set to None and self._velocities is None, that's because it was either not input or the user wants a default velocity grid
            if "combined" not in self.wavelengths:
                raise ValueError("Trying to set velocities (as None) but the wavelengths have not been set.\n" \
                                 "Please set your own velocity grid (highly recommend).\n"\
                                 "Otherwise, set the inputs with Data.set_inputs() to guess a -25 to 25 km/s grid based on those wavelengths.")
            if self.config.verbose >= 1:
                print("Velocity grid not input, using a grid calculated from input wavelengths with default range of -25 to 25 km/s.\n " \
                "It is highly recommended to input your own velocity grid, especially if you need a different sampling or velocity range.")
            deltav = utils.calc_deltav(self.wavelengths["combined"])
            self._velocities = np.arange(-25, 25 + deltav, deltav) # default velocity grid from -25 to 25 km/s with spacing calculated from input wavelengths

        else:
            # If the user is trying to set velocities to None, but they already exist, we don't want to reset them to None
            if self.config.verbose >= 1:
                print("Warning: You are trying to set the velocity grid to None, but it already exists. The existing velocity grid will be kept.")

    @property
    def linelist(self) -> LineList|None:
        """Returns the internally stored linelist. It has keys "wavelengths" and "depths" or index 0 and 1."""
        if self._linelist is None:
            return None

        self._validate_profile_groups(self._linelist)

        return LineList(self._linelist)

    @linelist.setter
    def linelist(self, linelist:Array2D|str|LineList|dict[str,Array1D]|None) -> None:
        """
        Sets the linelist for the data object. The linelist formats follows that of the doccumentation in the :py:class:`Acid` class,
        which then internally uses this function to set the linelist in the data object. The linelist is stored as a dictionary with 
        keys "wavelengths" and "depths", but is exposed as a :py:class:`LineList` object when accessed through the property. The LineList
        class allows for easy access to plotting, indexing, and validation.

        Parameters
        ----------
        linelist : Array2D, str, LineList, dict[str, Array1D], or None
             The linelist to be set, which can be in various formats for convenience.
             See :py:class:`Acid` init for the accepted linelist formats and parameters.
        """
        # Check if linelist already exists, override with new inputs if provided
        if linelist is not None:
            # The method names are self explaining, see the respective methods for more details on their process
            linelist_wl, linelist_depths = LineList.validate_linelist(linelist)
            linelist_wl, linelist_depths = LineList.drop_invalid_lines(linelist_wl, linelist_depths, verbose=self.config.verbose)

            # Check if the new linelist is different from the existing one
            overwriting = False
            if self._linelist is not None:
                if len(self._linelist["wavelengths"]) != len(linelist_wl) or len(self._linelist["depths"]) != len(linelist_depths):
                    overwriting = True
                elif not np.allclose(self._linelist["wavelengths"], linelist_wl) or not np.allclose(self._linelist["depths"], linelist_depths):
                    overwriting = True

            # Set new linelist
            self._linelist = {"wavelengths": linelist_wl, "depths": linelist_depths}

            # Validate profile groups with the new linelist
            # If profile_groups is not None, this will check that it has the same length as the new linelist and is 1D.
            self._validate_profile_groups(self._linelist)

            # If overwriting, reset variables and warn
            if overwriting:
                if self.config.verbose >= 1:
                    print("Warning: the input linelist has been modified. \n" \
                    f"Resetting variables that need to be recalculated.\nThe velocity grid and input arrays will not be reset.")
                self.reset()

    def _validate_profile_groups(self, input_linelist) -> None:
        """To be called when setting/accessing a linelist if the config.profile_groups has not been validated with the current (validated) linelist."""
        if self.config.profile_groups is not None:
            self.config.profile_groups = np.asarray(self.config.profile_groups).copy()
            if self.config.profile_groups.ndim != 1:
                raise ValueError("profile_groups must be a 1D array. Using profile_groups with multiple frames is not supported.\n"
                "If you wish to use different frames, please first combine the frames yourself and then input the combined " \
                "spectrum with the corresponding profile_groups.")
            linelist_wavelengths = input_linelist["wavelengths"]
            if len(self.config.profile_groups) != len(linelist_wavelengths):
                raise ValueError(f"The inputted profile_groups must have the same length as the input linelist. "
                                    f"Got {len(self.config.profile_groups)} groups for {len(linelist_wavelengths)} lines.")

    def plot_linelist(self, idx:np.ndarray|list|None=None, bounds:tuple|list|None=None, fig_ax:tuple|None=None, return_fig:bool=False) -> None|tuple:
        """
        Plots the linelist points with their corresponding depths as delta-function lines.

        Parameters
        ----------
        idx : np.ndarray or list, optional
            The indices of the linelist points to plot. If None, plots all points.
        bounds : tuple or list, optional
            The wavelength bounds (min, max) to clip the linelist for plotting. If None, plots all points.
        fig_ax : tuple, optional
            A tuple of (figure, axis) objects to plot on. If None, a new figure and axis are created.
        return_fig : bool, optional
            If True, returns the figure and axis objects instead of displaying the plot.

        Returns
        -------
        tuple or None
            If return_fig is True, returns a tuple of (figure, axis) objects. Otherwise, returns None.
        """
        if self.linelist is None:
            raise ValueError("No linelist found. Please set a linelist before trying to plot it.")
        wl = self.linelist["wavelengths"]
        depths = self.linelist["depths"]

        if idx is not None:
            wl = wl[idx]
            depths = depths[idx]

        # Clip the linelist to the specified bounds if provided, and to the min_depth
        if bounds is not None:
            idx_in_bounds = (wl >= bounds[0]) & (wl <= bounds[1])
            wl = wl[idx_in_bounds]
            depths = depths[idx_in_bounds]

        # Plot linelist
        if fig_ax is None:
            fig, ax = plt.subplots(figsize=(15, 9))
        else:
            fig, ax = fig_ax

        ax.vlines(wl, 1, 1-depths, color='C0', alpha=0.7)
        ax.set_title('Line List')
        ax.set_xlabel('Wavelength (Angstroms)')
        ax.set_ylabel('Relative Line Depth')
        ax.legend()
        if return_fig:
            return fig, ax
        utils.show_or_save(plt, self.config.figure_dir, "linelist.png", self.config.verbose)

    # Store config as a property for handling it to/from dictionary on saving
    @property
    def config(self) -> Config:
        """Returns the internally stored config object, which contains the configuration of the ACID run."""
        return self._config

    @config.setter
    def config(self, value: Config) -> None:
        """Sets the internally stored config object."""
        self._config = value

    def set_inputs(
        self,
        input_wavelengths: Array1D|Array2D|None        = None,
        input_flux:        Array1D|Array2D|None        = None,
        input_errors:      Array1D|Array2D|None        = None,
        input_sn:          Array1D|Array2D|Scalar|None = None,
        skips:             IntLike|None                = None,
    ) -> None:
        """Sets the input data for the ACID class. This is used to initialize the data object with the raw spectra,
        and to validate the arguments (previously done within the ACID function).
        Parameters
        ----------
        input_wavelengths : np.ndarray, optional
            Wavelength array for the input spectra, by default None
        input_flux : np.ndarray, optional
            Flux array for the input spectra, by default None
        input_errors : np.ndarray, optional
            Error array for the input spectra, by default None
        input_sn : np.ndarray, optional
            Signal-to-noise array for the input spectra, by default None
        skips : int, optional
            Allows you to set and override the Config value for skips if skips is not None.
            This allows the inputs to only set one in every skips pixels and is only recommended for testing.
            By default None, and uses the Config default value (1, no skipping).
        """
        # Check if inputs already exist, use a key to name dictionary map to get boolean for if any/all exist for following logic checks
        input_keys = ["wavelengths", "flux", "errors"]
        inputs = {
            "wavelengths": input_wavelengths,
            "flux": input_flux,
            # As of 1.5, SN or errors are guessed from the errors if one is not input, so treat them as a pair
            "errors": input_errors if input_errors is not None else input_sn,
        }
        inputs_already_exist = all(
            getattr(self, attr).get("input", None) is not None for attr in input_keys
        )
        all_inputs_not_none = all(inputs[attr] is not None for attr in input_keys)
        any_inputs_not_none = any(inputs[attr] is not None for attr in input_keys)
        del inputs # it was just a trick to do the input checks in a loop

        # Handle logic for already existing inputs, more or less described in the print statements
        if inputs_already_exist:
            if not all_inputs_not_none and any_inputs_not_none:
                if self.config.verbose >= 1:
                    print(f"Warning: input wavelengths, flux, and errors are already set in the class. \n" \
                        f"Some of the inputs you provided are None. \n" \
                        f"If you are trying to update the input wavelengths, flux, or errors, you must provide all 3. \n"
                        f"The current input wavelengths, flux, and errors will be kept.")
                self.combine_spec(output=False)
                return
            elif not any_inputs_not_none:
                if self.config.verbose >= 3:
                    print("Input wavelengths, flux, and errors are already set in the class. Keeping existing values.")
                self.combine_spec(output=False)
                return
            # Else continue with the rest of the function to update inputs, later on, the code will check if new inputs are 
            # different from the existing ones, if so, deletes variables that need to be recalculated.
        else:
            if not all_inputs_not_none:
                raise ValueError("input_wavelengths, input_flux, and (input_errors or input_sn) must be provided either as arguments " \
                                 "or in the form of a Data object.")
        
        # First check we have not received len=0 or len=1 for wavelengths and flux so that they do not collapse to 0 dimensions on squeezing
        if input_wavelengths is not None and len(input_wavelengths) <= 1:
            raise ValueError("input_wavelengths must have more than 1 value to be valid.")
        if input_flux is not None and len(input_flux) <= 1:
            raise ValueError("input_flux must have more than 1 value to be valid.")
        if input_errors is not None and len(input_errors) <= 1:
            raise ValueError("input_errors must have more than 1 value to be valid.")

        # Convert to arrays, squeeze to remove extra dimensions (as default in legacy inputs)
        try:
            input_wavelengths = np.array(input_wavelengths).squeeze()
            input_flux = np.array(input_flux).squeeze()
            input_errors = np.array(input_errors).squeeze() if input_errors is not None else None
            input_sn = np.array(input_sn).squeeze() if input_sn is not None else None
        except:
            raise ValueError("There was an error converting the input wavelengths, flux, errors, or SN to numpy arrays. Exception message: \n" + tb.format_exc() + "\n")

        # Make any values < 0 or infinite equal to nan, which are gracefully later handled.
        if input_errors is not None:
            input_wavelengths, input_flux, input_errors = utils.mask_invalid(input_wavelengths, input_flux, input_errors, verbose=self.config.verbose)
        else:
            input_wavelengths, input_flux = utils.mask_invalid(input_wavelengths, input_flux, verbose=self.config.verbose)

        # Check that none of the inputs are all nan
        if np.all(np.isnan(input_wavelengths)) or np.all(np.isnan(input_flux)) or (input_errors is not None and np.all(np.isnan(input_errors))):
            raise ValueError("None of the input wavelengths, spectra, and errors can be all NaN. Check your inputs for invalid or negative values")

        # Get SN or errors if one is not provided
        if input_sn is None and input_errors is None:
            raise ValueError("One of input_sn or input_errors must be provided.")

        elif input_sn is None:
            input_sn = utils.guess_SNR(input_wavelengths, input_flux, input_errors)
            if self.config.verbose >= 2:
                print(f"No input_sn provided and was instead approximated. Guessed value(s):\n {input_sn}")

        elif input_errors is None:
            # Input SN can accidentally be input with the same shape as the wavelengths, so correct now if thats the case
            if input_sn.ndim == input_wavelengths.ndim:
                if self.config.verbose >= 2:
                    print("Per pixel S/N provided, taking the mean over the central 2/3 of the wavelengths to get a single S/N value for each frame.")
                # Per pixel S/N provided, take the mean over the central 2/3 of the wavelengths
                input_sn = utils.collapse_SNR(input_sn, input_wavelengths)

            input_errors = utils.guess_errors(input_flux, input_sn)
            if self.config.verbose >= 1:
                print(f"No input_errors provided and was instead approximated from the input S/N.\n"\
                      f"It is highly recommended to obtain correct per-pixel errors.")

        # Check they have matching shape
        if not input_wavelengths.shape == input_flux.shape == input_errors.shape:
            raise ValueError("Input wavelengths, spectra and spectral errors must all have the same shape.")

        # Ensure now that the SN becomes just a single value per frame
        if input_sn.ndim == input_wavelengths.ndim:
            if self.config.verbose >= 2:
                print("Per pixel S/N provided, taking the mean over the central 2/3 of the wavelengths to get a single S/N value for each frame.")
            # Per pixel S-N provided, take the mean over the central 2/3 of the wavelengths
            input_sn = utils.collapse_SNR(input_sn, input_wavelengths)
        elif input_sn.ndim != input_flux.ndim-1:
            raise ValueError("input_sn must be either a single-valued list/array with the average S/N for each frame, " \
            f"or an array of S/N values for each pixel. \n" \
            "The shape of the input input_sn does not match the number of frames in input_flux, " \
            "nor does it have one more dimension than input_flux.")
        if input_sn.ndim != input_flux.ndim - 1:
            raise ValueError(f"input_sn.ndim and input_flux.ndim-1 do not match, sn ndim = {input_sn.ndim}, flux ndim = {input_flux.ndim}")
        

        # Ensure all inputs are at least 2D (with the first dimension being the frame number), 
        # to ensure consistent handling of single-frame and multi-frame inputs. 
        input_wavelengths = np.atleast_2d(input_wavelengths)
        input_flux = np.atleast_2d(input_flux)
        input_errors = np.atleast_2d(input_errors)
        input_sn = np.atleast_1d(input_sn)

        if input_sn.shape[0] != input_flux.shape[0]:
            raise ValueError("The number of frames for the SN must match the number of frames in wavelengths, flux, and errors.")

        # Ensure data is sorted by wavelength
        sort_idx = np.argsort(input_wavelengths, axis=-1)
        input_wavelengths = np.take_along_axis(input_wavelengths, sort_idx, axis=-1)
        input_flux = np.take_along_axis(input_flux, sort_idx, axis=-1)
        input_errors = np.take_along_axis(input_errors, sort_idx, axis=-1)

        # Apply skips, this just skips some data for testing and faster runs, but real runs should always leave skips=1
        self.config.skips = skips # no change if skips is None
        input_wavelengths = input_wavelengths[:, ::self.config.skips]
        input_flux       = input_flux[:, ::self.config.skips]
        input_errors     = input_errors[:, ::self.config.skips]

        # In case these are set when input values already exist, check if they are the same, if not, reset variables to be recalculated.
        # This checks basically if self.wavelengths["input"] is the same as input_wavelengths, and same for flux and errors, if they exist. 
        overwriting = False
        for check in ["wavelengths", "flux", "errors", "sn"]:
            if getattr(self, check).get("input", None) is not None and eval(f"input_{check}") is not None:
                if getattr(self, check)["input"].shape != eval(f"input_{check}").shape:
                    overwriting = True
                elif not np.allclose(getattr(self, check)["input"], eval(f"input_{check}"), equal_nan=True):
                    overwriting = True

        # Set inputs to class variables, the self.reset() cleans all arrays except for the inputs, so this is safe
        self.wavelengths["input"] = input_wavelengths
        self.flux["input"]        = input_flux
        self.errors["input"]      = input_errors
        self.sn["input"]          = input_sn

        # If reset is needed, reset calculated values to force recalculation with new inputs and warn the user
        if overwriting:
            if self.config.verbose >= 1:
                print("Warning: input wavelengths, flux, or errors have been changed from their previous values. \n" \
                f"Resetting variables that need to be recalculated.\nThe velocity grid and linelist will not be reset.")
            self.reset(preserve_combined=False)

        # Now generate the combined dataset (previously done in Acid class)
        # Combines spectra from each frame (weighted based of S/N), returns to S/N of combined spectra.
        # If only one frame, just uses that frame. We also check if this step has already been done and skips if so.
        self.combine_spec(output=False)

    def combine_spec(
        self,
        frame_wavelengths: Array1D|Array2D|None = None,
        frame_flux:        Array1D|Array2D|None = None,
        frame_errors:      Array1D|Array2D|None = None,
        frame_sns:         Array1D|Array2D|None = None,
        output:            bool                 = True
        ) -> tuple | None:
        """
        Combines the multiple inputted spectral frames into one spectrum, or just passes through the single frame if only one was input. 
        The frames are interpolated onto a common wavelength grid of the spectrum with the highest S/N, and then a weighted average is used based on the errors. 
        The S/N of the combined spectrum is also calculated based on the input S/N and the weights.

        Parameters
        ----------
        frame_wavelengths : :py:type:`Array1D` | :py:type:`Array2D`, optional
            Wavelengths for the spectral frames, by default None
        frame_flux : :py:type:`Array1D` | :py:type:`Array2D`, optional
            Fluxes for the spectral frames, by default None
        frame_errors : :py:type:`Array1D` | :py:type:`Array2D`, optional
            Errors for the spectral frames, by default None
        frame_sns : :py:type:`Array1D` | :py:type:`Array2D`, optional
            Signal-to-noise ratio for the spectral frames, by default None
        output : bool, optional
            Whether to output the combined spectrum, by default True

        Returns
        -------
        tuple | None, if output is True, containing:
            combined_wavelengths : np.ndarray
                Wavelengths for the combined spectrum
            combined_spectrum : np.ndarray
                Fluxes for the combined spectrum
            combined_errors : np.ndarray
                Errors for the combined spectrum
            combined_sn : float
                Signal-to-noise ratio for the combined spectrum
        None, if output is False, but the combined spectrum is still saved in the data class attributes.
        """

        if frame_wavelengths is not None: # This should only be for testing
            self.wavelengths["input"] = np.copy(frame_wavelengths)
            self.flux["input"]        = np.copy(frame_flux)
            self.errors["input"]      = np.copy(frame_errors)
            self.sn["input"]          = np.copy(frame_sns)

        # Set simple names for variables (just used in this function)
        wavelengths = np.copy(self.wavelengths["input"])
        flux        = np.copy(self.flux["input"])
        errors      = np.copy(self.errors["input"])
        sn          = np.copy(self.sn["input"])

        # Return as is if only one spectrum
        if len(self.wavelengths["input"])==1:
            combined_wavelengths = wavelengths[0]
            combined_flux        = flux[0]
            combined_errors      = errors[0]
            combined_sn          = sn[0]

            self.wavelengths["combined"] = combined_wavelengths
            self.flux["combined"]        = combined_flux
            self.errors["combined"]      = combined_errors
            self.sn["combined"]          = combined_sn

        else:
            # Get wavelength grid with highest S/N
            combined_wavelengths = wavelengths[np.argmax(sn)]

            interpolated_flux   = np.zeros_like(flux)
            interpolated_errors = np.zeros_like(errors)

            # combine all spectra to one spectrum
            for n in range(len(flux)):

                # Interpolate each spectrum onto the combined wavelength grid
                f2 = interp1d(wavelengths[n], flux[n], kind = 'linear', bounds_error=False, fill_value = 'extrapolate')
                f2_err = interp1d(wavelengths[n], errors[n], kind = 'linear', bounds_error=False, fill_value = 'extrapolate')
                interpolated_flux[n] = f2(combined_wavelengths)
                interpolated_errors[n] = f2_err(combined_wavelengths)

                # Mask out out extrapolated areas
                idx_ex = np.logical_and(combined_wavelengths<=np.max(wavelengths[n]),
                                        combined_wavelengths>=np.min(wavelengths[n]))
                idx_ex = tuple([idx_ex==False])

                interpolated_flux[n][idx_ex] = 1.
                interpolated_errors[n][idx_ex] = 1e12

                # Mask out nans and zeros (these do not contribute to the main spectrum)
                where_are_NaNs = np.isnan(interpolated_flux[n])
                interpolated_errors[n][where_are_NaNs] = 1e12
                where_are_zeros = np.where(interpolated_flux[n] == 0)[0]
                interpolated_errors[n][where_are_zeros] = 1e12

                where_are_NaNs = np.isnan(interpolated_errors[n])
                interpolated_errors[n][where_are_NaNs] = 1e12
                where_are_zeros = np.where(interpolated_errors[n] == 0)[0]
                interpolated_errors[n][where_are_zeros] = 1e12

            invvars = 1 / interpolated_errors**2
            invvars[interpolated_errors >= 1e12] = 0

            weights = np.sum(invvars, axis=0)
            non_zero = weights > 0
            
            weighted_flux   = np.sum(interpolated_flux * invvars, axis=0)
            
            combined_flux = np.full_like(weights, 1.0)      # or np.nan
            combined_errors = np.full_like(weights, 1e12)

            combined_flux[non_zero] = weighted_flux[non_zero] / weights[non_zero]
            combined_errors[non_zero] = 1 / np.sqrt(weights[non_zero])

            frame_weights = np.sum(invvars, axis=1)
            combined_sn   = np.sum(frame_weights * sn) / np.sum(frame_weights)

            self.wavelengths["combined"] = combined_wavelengths
            self.flux["combined"]        = combined_flux
            self.errors["combined"]      = combined_errors
            self.sn["combined"]          = combined_sn

        # Clean combined spectra of NaNs
        wavelengths, flux, errors, nanmask = utils.drop_invalid(self.wavelengths["combined"], self.flux["combined"],
                                                                self.errors["combined"], return_mask=True)
        self.wavelengths["combined"] = wavelengths
        self.flux["combined"] = flux
        self.errors["combined"] = errors
        self.nanmask = nanmask

        if output is True:
            # ie if called as a function rather than from ACID function
            return (
            self.wavelengths["combined"],
            self.flux["combined"],
            self.errors["combined"],
            self.sn["combined"]
        )

    def reset(self, preserve_combined:bool=True) -> None:
        """
        Resets all derived states while preserving:
        - raw input arrays
        - combined spectrum, unless explicitly invalidated
        - linelist
        - velocity grid
        - Config
        """
        # Preserve desired inputs
        inputs = {}
        for name in ("wavelengths", "flux", "errors", "sn"):
            value = getattr(self, name).get("input", None)
            inputs[name] = None if value is None else value.copy()

        combined = {}
        for name in ("wavelengths", "flux", "errors", "sn"):
            value = getattr(self, name).get("combined", None)
            combined[name] = copy.deepcopy(value)

        nanmask = (
            None if self.nanmask is None
            else self.nanmask.copy()
        )

        # Preserve these directly rather than through their property setters,
        # otherwise the setters can trigger reset() again.
        linelist = copy.deepcopy(self._linelist)
        velocities = (
            None if self._velocities is None
            else self._velocities.copy()
        )
        config = self._config

        # Reinitialise every dataclass field to its default.
        self.__init__()

        # Restore persistent state
        self._config = config
        self._linelist = linelist
        self._velocities = velocities

        # Restore desired values
        if preserve_combined:
            for name, value in combined.items():
                if value is not None:
                    getattr(self, name)["combined"] = value
            self.nanmask = nanmask

        # Restore raw inputs
        for name, value in inputs.items():
            if value is not None:
                getattr(self, name)["input"] = value

    def plot_continuum_fit(self, key:str="masked", return_fig:bool=False, save_fig:str|None=None) -> None|tuple:
        """
        Plots the result of the continuum fitting step, showing the original spectrum, the fitted continuum, and the clipped points used for the continuum fit.

        Parameters
        ----------
        key : str, optional
            The type of continuum fit to plot and pull the data from, either "initial" for the initial continuum fit or
            "masked" for the continuum fit after residual masking. Default is "masked".
        return_fig : bool, optional
            Whether to return the figure and axis objects instead of showing the plot, by default False.
        save_fig : str or None, optional
            If provided, the path to save the figure. If None, the figure will not be saved. Default is None.
        """
        # Check we have all inputs needed for plot
        if key not in ["initial", "masked"]:
            raise ValueError("key must be either 'initial' or 'masked' (these are the only two steps that produce a scipy continuum fit).")
        if key not in self.plotting_variables:
            raise ValueError(f"No plotting variables found for key={key!r}. " \
                             "Please ensure that the continuum fit has been performed for this key.")
        if not all(
            attr in self.plotting_variables[key] for attr in [
                "clipped_waves", "clipped_flux", "good"]
            ):
            raise ValueError("To plot the continuum fit, please first run the continuum fitting in ACID step for the specified plot_type.")

        # Unpack variables
        good                     = self.plotting_variables[key]["good"]
        clipped_waves            = self.plotting_variables[key]["clipped_waves"]
        clipped_flux             = self.plotting_variables[key]["clipped_flux"]

        # Normalise wavelengths and plot flux and fit
        fig, ax = plt.subplots(figsize=(15, 9))
       
        ax.plot(self.wavelengths[key], self.flux[key], label='Original Spectrum', color="C0", alpha=0.7)
        ax.plot(self.wavelengths[key], self.continuum[key], label='Fitted Continuum', color='red')
        a, b = utils.get_normalisation_coeffs(self.wavelengths[key])
        ax.plot((clipped_waves[good]-b)/a, clipped_flux[good], 'o', label='Continuum Normalized Spectrum', color='green')

        # Plot the linelist points, with a color corresponding to their depth in the linelist within the range
        # Only plot the 20 strongest lines to avoid overcrowding.
        ll_wl = self.linelist["wavelengths"]
        ll_depths = self.linelist["depths"]
        from ..lsd import LSD
        ll_wl, ll_depths, _ = LSD.clip_wavelengths(self.wavelengths[key], ll_wl, ll_depths)
        idx = np.argsort(ll_depths)
        ll_wl = ll_wl[idx]
        ll_depths = ll_depths[idx]
        ll_wl = ll_wl[-20:]
        ll_depths = ll_depths[-20:]

        # Try colouring them, but often the linelist points will be outside the wavelength range so just skip if 
        # there's an error to avoid breaking the plot
        try:
            cmap = plt.cm.viridis_r
            norm = mpl.colors.Normalize(vmin=np.nanmin(ll_depths), vmax=np.nanmax(ll_depths))
            for i, (wl, depth) in enumerate(zip(ll_wl, ll_depths)):
                ax.axvline(
                    wl,
                    color=cmap(norm(depth)),
                    linestyle="--",
                    alpha=1,
                    label="Line List (20 strongest lines in region)" if i == 0 else None,
                )
            # Create colorbar for depth
            sm = mpl.cm.ScalarMappable(norm=norm, cmap=cmap)
            sm.set_array([])  # needed for some matplotlib versions
            cbar = fig.colorbar(sm, ax=ax)
            cbar.set_label("Line depth")
        except:
            if self.config.verbose >= 1:
                print("There was an error plotting the linelist points, most likely your linelist range is outside your wavelength range.")
            pass

        # Plot the line masks with their names
        x = self.wavelengths[key]
        line_mask = self.config.masking_lines.get_masks(x, with_names=True)
        for i, (name, masks) in enumerate(line_mask.items()):
            padded = np.concatenate(([False], masks, [False]))
            starts = np.flatnonzero(~padded[:-1] & padded[1:])
            ends   = np.flatnonzero(padded[:-1] & ~padded[1:])
            for j, (start, end) in enumerate(zip(starts, ends)):
                ax.axvspan((x[start]), (x[end-1]), color=f'C{i+2}', alpha=0.3,
                        label=f"{name} Line masks" if j == 0 else None)
        
        # Plot the other two masking regions if in the masked plot type, these masking are only done after the initial fit
        if key == "masked":
            masked = self.pix_mask | self.sigma_mask
            padded = np.concatenate(([False], masked, [False]))
            starts = np.flatnonzero(~padded[:-1] & padded[1:])
            ends   = np.flatnonzero(padded[:-1] & ~padded[1:])
            for i, (start, end) in enumerate(zip(starts, ends)):
                ax.axvspan((x[start]), (x[end-1]),
                            color='red', alpha=0.15, label="Sigma masking and pixel deviation regions" if i == 0 else None)

        # Add labels and legend, and save or show figure
        plot_title = "Initial Continuum Fit" if key == "initial" else "Continuum Fit after Residual Masking"
        ax.set_title(plot_title)
        ax.legend()
        ax.set_ylim(np.min(self.flux[key])*0.9, np.max(self.flux[key])*1.1)
        if save_fig is not None:
            plt.savefig(save_fig)
        if return_fig:
            return fig, ax
        title = "continuum_fit_initial.png" if key == "initial" else "continuum_fit_masked.png"
        utils.show_or_save(plt, self.config.figure_dir, title, self.config.verbose)

    def plot_residual_masking(self) -> None:
        """
        Creates 3 plots to show the result of the residual masking step, showing the residuals with the sigma clipping thresholds, 
        the masked regions, and the initial profile after masking.
        """
        # Check we have all inputs needed for plot
        if "masked" not in self.plotting_variables:
            raise ValueError("No plotting variables found for masking. Residual masking likely has not been performed in Acid.")
        if "masked" not in self.wavelengths and "masked" not in self.flux:
            raise ValueError("No masked wavelengths or fluxes found. Please ensure that the residual masking step has been performed")

        # Unpack variables
        x = self.wavelengths["combined"]
        y = self.flux["combined"]
        residuals = self.residuals["masked"]
        upper_clip = self.plotting_variables["masked"]["upper_clip"]
        lower_clip = self.plotting_variables["masked"]["lower_clip"]
        uc_finite = np.isfinite(upper_clip) # useful for plotting
        lc_finite = np.isfinite(lower_clip)
        pix_mask = self.pix_mask
        line_mask = self.line_mask
        full_mask = self.full_mask

        nremoved = np.sum(full_mask)
        if self.config.verbose >= 2:
            print(f"{nremoved}/{len(residuals)} pixels were removed after residual masking.")

        # Create plot and add residuals with sigma clipping thresholds and masked regions
        fig, ax = plt.subplots(figsize=(15, 9))
        ax.axhline(0, color='black', linestyle='--', linewidth=1)

        utils.plot_masked_line(ax, x, residuals, ~full_mask, colors=["blue", "red"], label=["Residuals", "Masked Residuals"])

        # Show sigma clipping
        if uc_finite:
            ax.axhline(upper_clip, color='C0', linestyle='--', label='Sigma Clip Thresholds', linewidth=2)
        if lc_finite:
            lc_label = 'Sigma Clip Thresholds' if not uc_finite else None
            ax.axhline(lower_clip, color='C0', linestyle='--', linewidth=2, label=lc_label)

        # Show line masking regions
        line_mask = self.config.masking_lines.get_masks(x, with_names=True)
        for i, (name, masks) in enumerate(line_mask.items()):
            padded = np.concatenate(([False], masks, [False]))
            starts = np.flatnonzero(~padded[:-1] & padded[1:])
            ends   = np.flatnonzero(padded[:-1] & ~padded[1:])
            for j, (start, end) in enumerate(zip(starts, ends)):
                ax.axvspan((x[start]), (x[end-1]), color=f'C{i+2}', alpha=0.3,
                           label=f"{name.capitalize()} line masks" if j == 0 else None)

        # Show pix_chunk masked points:
        masked = pix_mask
        padded = np.concatenate(([False], masked, [False]))
        starts = np.flatnonzero(~padded[:-1] & padded[1:])
        ends   = np.flatnonzero(padded[:-1] & ~padded[1:])
        for i, (start, end) in enumerate(zip(starts, ends)):
            ax.axvspan((x[start]), (x[end-1]),
                        color='red', alpha=0.15, label="Applied chunk deviation masking" if i == 0 else None)
        
        # And show chunk deviation range
        dev = self.config.dev_perc / 100
        ax.hlines([-dev, dev], xmin=np.min(x), xmax=np.max(x), color='C1', linestyle='--', linewidth=2, label="Chunk deviation masking range")

        # Set a good ylim off everything but the masked points
        ymax = np.nanmax([dev, upper_clip if uc_finite else np.nan, np.max(residuals[~full_mask])])
        ymin = np.nanmin([-dev, lower_clip if lc_finite else np.nan, np.min(residuals[~full_mask])])
        diff = (ymax - ymin) * 0.1 # Set an even 10% buffer on either side of max/min
        ax.set_ylim(ymin - diff, ymax + diff)

        ax.set_xlim(np.min(x), np.max(x))
        ax.grid(True)
        ax.set_title('Residuals with Sigma Clipping Thresholds')
        ax.set_xlabel('Wavelength')
        ax.set_ylabel('Residuals')
        ax.legend()
        utils.show_or_save(plt, self.config.figure_dir, "masking_residuals.png", self.config.verbose)

        # Plot the LSD profile
        fig, ax = plt.subplots(figsize=(10, 6))
        try:
            ax.plot(self.velocities, self.profile["masked"][0], label='LSD Profile after Masking and before sampling', color='red')
        except:
            ax.plot(self.velocities, np.median(self.profile["masked"][0], axis=0), label='MEDIAN LSD Profile after Masking and before sampling', color='red')
        ax.set_title('LSD Profile after Residual Masking')
        ax.set_xlabel('Velocity (km/s)')
        ax.set_ylabel('LSD Profile')
        ax.axhline(1, color='black', linestyle='--')
        ax.legend()
        ax.grid(True)
        utils.show_or_save(plt, self.config.figure_dir, "masking_profile.png", self.config.verbose)

        # Finally plot the forward model
        x = self.wavelengths["combined"]
        y = self.flux["combined"]
        forward = self.forward_y["masked"]
        continuum = self.continuum["masked"]
        residuals = (y - forward) / forward
        fig, ax = plt.subplots(2, 1, figsize=(15, 12), gridspec_kw={'height_ratios': [3, 1]}, sharex=True)
        ax[0].plot(x, y, label='Original data', color='black', linewidth=1)
        ax[0].plot(x, continuum, color='C1', linewidth=1, label='Fitted Continuum', linestyle='--')
        utils.plot_masked_line(ax[0], x, forward, ~full_mask, label=["Forward model", "Masked Forward model"])
        ax[0].set_title('Masked Forward Model')
        ax[0].set_ylabel('Flux')
        ax[0].grid(True)
        ax[0].legend()
        
        utils.plot_masked_line(ax[1], x, residuals, ~full_mask, label=["Residuals", "Masked Residuals"])
        ax[1].axhline(0, color='black', linestyle='--', linewidth=1)

        ymax = np.max(residuals[~full_mask])
        ymin = np.min(residuals[~full_mask])
        diff = (ymax - ymin) * 0.1 # Set an even 10% buffer on either side of max/min
        ax[1].set_ylim(ymin - diff, ymax + diff)

        ax[1].grid(True)
        # ax[1].set_title('Residuals of forward model with masked residuals')
        ax[1].set_xlabel('Wavelength')
        ax[1].set_ylabel('Residuals')
        ax[1].legend()
        plt.tight_layout()

        utils.show_or_save(plt, self.config.figure_dir, "initial_forward_model.png", self.config.verbose)

    def save(self, save_path:str|None=None, sampler_path:str|None=None) -> None:
        """
        Saves the data object to a file using pickling. This will store just the dictionary of the class, 
        not the actual class itself. The load function then will initialise a new Data class using the dictionary.

        Parameters
        ----------
        save_path : str | None
            The path to save the data object. If None, uses the path stored in the config.
            If That is also None, the data object will not be saved.
            Will create only the final parent directory for the filepath if it does not exist.
            The parent's parent must already exist.
            The file must end with .pkl to be recognised as a pickled file.
        sampler_path : str | None
            This is used for saving the sampler as a HDF5 file if it has not already been set up as such.
            If a .h5 file is provided, and the sampler is not already saved as a HDF5 file, the sampler backend is converted to a HDF5 backend and saved.
            If the sampler is already set up to save as a HDF5 file, this argument is ignored. 
            If you want to move the file location, move it yourself and set Data.sampler = sampler_path to update the location in the Data object.
            If None, this will do nothing.
        """
        # First we handle the sampler saving, so that when saved it can be added to the sampler path saved in the dictionary later
        if sampler_path is not None:
            # Convert to abspath
            sampler_path = os.path.abspath(sampler_path)
            if self.sampler is not None:
                if not isinstance(self.sampler.backend, HDFBackend):
                    if not sampler_path.endswith(".h5"):
                        raise ValueError("sampler_path must end with .h5 to convert and save the sampler backend as a HDF5 file.")
                    utils.ensure_directory(os.path.dirname(sampler_path), "sampler directory")
                    utils.save_backend_to_hdf5(self.sampler.backend, sampler_path)
                    self.config.sampler_path = sampler_path # update config with sampler path for future reference
                    if self.config.verbose >= 2:
                        print(f"Sampler backend converted and saved as HDF5 file to {sampler_path}")
                else:
                    if self.config.verbose >= 2:
                        print("Sampler is already set up to save as a HDF5 file, ignoring sampler_path argument.")
            else:
                if self.config.verbose >= 1:
                    print("Cannot save sampler as sampler does not exist.")

        # TODO: NEEDS UPDATING WITH NEW CONFIG DIR, maybe move them all to Config properties?
        # Now save the Data object itself, with the sampler path included to be used when reloaded
        save_path = os.path.abspath(save_path) if save_path is not None else None
        self.config.save_path = save_path # update and overwrite config with save path for future reference
        save_path = self.config.save_path # now use the save path in the config
        if save_path is None:
            if self.config.verbose >= 1:
                print("No save_path exists or was provided. The Data instance will not be saved.")
            return

        payload = self.to_dict() # generates a dictionary of the data object for easy pickling

        save_dir = os.path.dirname(os.path.abspath(save_path))
        utils.ensure_directory(save_dir, "data directory")
        with open(save_path, "wb") as f:
            pickle.dump(payload, f, protocol=pickle.HIGHEST_PROTOCOL)
        if self.config.verbose >= 2:
            print(f"Data object saved to {save_path}")

    @classmethod
    def load(cls, filename:str) -> Data:
        """
        Loads a data object from a file using pickling. This will read the dictionary from the file and 
        then use it to initialise a new Data class.

        Parameters
        ----------
        filename : str
            The name of the file to load the data object from. This should be a .pkl file.
        Returns
        -------
        Data
            The loaded data object.
        """
        with open(filename, "rb") as f:
            payload = pickle.load(f)

        # Initialise a new Data object and update it with the payload dictionary
        return cls().from_dict(payload)

    def to_dict(self) -> dict[str, Any]:
        """
        Converts the data object to a dictionary payload for saving. This is used internally in the save method, 
        but can also be used for debugging or other purposes.
        """
        if self.sampler is not None and self.config.sampler_type == "dynesty":
            raise ValueError("Storing the sampler is not currently supported for dynesty samplers.\n" \
            "If you really want to, separate the sampler with data.sampler.save('sampler') and add it back later.\n")

        payload: dict[str, Any] = {}
        for f in fields(self):
            name = f.name
            val = getattr(self, name)

            if name == "_config":
                payload["config"] = val.to_dict() # store as dict in payload, but store as class in Data
            elif name == "_sampler":
                if val is not None:
                    if self.config.sampler_path is not None:
                        payload["sampler"] = self.config.sampler_path # stores just the path to the sampler
            else:
                payload[name] = val

        return payload

    def from_dict(self, payload:dict[str,Any]) -> Data:
        """
        Updates the data object from a dictionary payload. This is used internally in the 
        load method, but can also be used for debugging or other purposes.

        Parameters
        ----------
        payload : dict
            The dictionary payload to update the data object from. This should have the same keys as the
            attributes of the data class. The "config" key should be a dictionary 
            that can be used to initialise a Config class.
        """
        for f in fields(self):
            name = f.name
            if name == "_config": # config stored as a dict in payload, but stored here as class
                cfg_dict = payload.get("config", {})
                setattr(self, "_config", Config(**cfg_dict))
            elif name == "_sampler":
                continue # handled after loop
            else:
                if name in payload:
                    setattr(self, name, payload[name])

        # Handle sampler separately
        self.sampler = payload.get("sampler", None) # property handles the loading of the sampler
        if self.sampler is None and self.config.sampler_path is not None:
            try:
                self.sampler = self.config.sampler_path
            except:
                self.sampler = None

        return self

    @property
    def result(self):
        if self.exception is not None:
            if self.config.verbose >= 1:
                print(f"An exception was raised during the run, cannot return results object.\n"
                      f"Returning None instead.")
            return None
        if self.complete is False:
            if self.config.verbose >= 1:
                print(f"Results for order {self.config.order} have not yet been calculated, cannot return results object.\n"
                      f"Returning None instead.")
            return None
        from ..result import Result
        return Result(self)
